#!/bin/bash
_node_name="server-`ec2metadata --instance-id`"
rm -rf /etc/chef/client.pem
echo "node_name '$_node_name'" >> /etc/chef/client.rb
chef-client -N "$_node_name" -o role["base"]


#cloud-config
users:
  - name: demo
    gecos: Demo Account
    lock-passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv60WjxoM39LgPDbiW7ne3gu18q0NIVv0RE6rDLNal1quXZ3nqAlANpl5qmhDQ+GS/sOtygSG4/9aiOA4vXO54k1mHWL2irjuB9XbXr00+44vSd2q/vtXdGXhdSMTf4/XK17fjKSG/9y3yD6nml6q9XgQxx9Vf/IkaKdlK0hbC1ds0+8h83PTb9dF3L7hf3Ch/ghvj5++tWJFdFeG+VI7EDuKNA4zL8C5FdYYWFA88YAmM8ndjA5qCjZXIIeZvZ/z9Kpy6DL0QZ8T3NsxRKapEU3nyiIuEAmn8fbnosWcsovw0IS1Hz6HsjYo4bu/gA82LWt3sdRUBZ/7ZsVD3ELip user@example.com
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_pwauth: true
    shell: /bin/bash
    passwd: {hash password}

    
Create hash password:
# yum install -y expect
# mkpasswd --method=SHA-512 --rounds=4096
or
# openssl passwd -1
